alpha: 0.75
batchsize: 64
dropout_linears:
- 0.4
- 0.2
gamma: 2
in_channels: 343
lr: 0.00015
max_epochs: 20
monitor: valid_S
name: dls-suc
num_linears:
- 700
- 220
patience: 6
seqlen: 33
train_way: 1
